import { getAllEmergencyData } from '~/data/emergency'

/**
 * Generates a printable HTML emergency guide from cached data
 * Opens in a new window for printing as PDF
 */
export function generateEmergencyPDF() {
    const data = getAllEmergencyData()

    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Emergency Guide - Sri Lanka</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 20px; max-width: 800px; margin: 0 auto; line-height: 1.5; }
    h1 { color: #dc2626; margin-bottom: 10px; font-size: 24px; }
    h2 { color: #374151; margin: 20px 0 10px; font-size: 18px; border-bottom: 2px solid #dc2626; padding-bottom: 5px; }
    h3 { color: #6b7280; font-size: 14px; margin-top: 15px; }
    .emergency-number { background: #fef2f2; border: 2px solid #dc2626; border-radius: 8px; padding: 15px; margin: 10px 0; }
    .emergency-number .name { font-weight: bold; font-size: 16px; color: #dc2626; }
    .emergency-number .number { font-size: 24px; font-weight: bold; color: #1f2937; }
    .emergency-number .desc { font-size: 12px; color: #6b7280; margin-top: 5px; }
    .embassy { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; margin: 8px 0; }
    .embassy .country { font-weight: bold; color: #1f2937; }
    .embassy .details { font-size: 12px; color: #6b7280; }
    .phrase { background: #fef3c7; border-radius: 8px; padding: 12px; margin: 8px 0; }
    .phrase .english { font-weight: bold; color: #92400e; }
    .phrase .translations { font-size: 14px; margin-top: 5px; }
    .hospital { background: #ecfdf5; border: 1px solid #10b981; border-radius: 8px; padding: 12px; margin: 8px 0; }
    .hospital .name { font-weight: bold; color: #065f46; }
    .hospital .phone { font-size: 16px; font-weight: bold; color: #1f2937; }
    .print-note { background: #dbeafe; padding: 10px; border-radius: 8px; margin-bottom: 20px; font-size: 12px; color: #1e40af; }
    @media print { .print-note { display: none; } body { padding: 0; } }
  </style>
</head>
<body>
  <div class="print-note">
    📄 <strong>Print this page</strong> (Ctrl/Cmd + P) to save as PDF for offline use.
  </div>

  <h1>🚨 Emergency Guide - Sri Lanka</h1>
  <p style="color: #6b7280; margin-bottom: 20px;">Keep this guide accessible for emergencies. All numbers work offline.</p>

  <h2>🆘 Emergency Numbers</h2>
  ${data.emergencyNumbers.map(n => `
    <div class="emergency-number">
      <div class="name">${n.name}</div>
      <div class="number">📞 ${n.primaryNumber}</div>
      ${n.secondaryNumber ? `<div style="font-size: 14px; color: #6b7280;">Alt: ${n.secondaryNumber}</div>` : ''}
      <div class="desc">${n.description}</div>
    </div>
  `).join('')}

  <h2>🏛️ Embassies & Consulates</h2>
  ${data.embassies.map(e => `
    <div class="embassy">
      <div class="country">${e.country} (${e.missionType})</div>
      <div class="details">📍 ${e.address}, ${e.city}</div>
      <div class="details">📞 ${e.phone}</div>
    </div>
  `).join('')}

  <h2>🗣️ Emergency Phrases</h2>
  ${data.emergencyPhrases.map(p => `
    <div class="phrase">
      <div class="english">${p.english}</div>
      <div class="translations">
        <strong>Sinhala:</strong> ${p.sinhala}<br>
        <strong>Tamil:</strong> ${p.tamil}<br>
        ${p.pronunciationHint ? `<em style="font-size: 12px; color: #78350f;">${p.pronunciationHint}</em>` : ''}
      </div>
    </div>
  `).join('')}

  <h2>🏥 Hospitals</h2>
  ${data.hospitals.map(h => `
    <div class="hospital">
      <div class="name">${h.name} (${h.type})</div>
      <div style="font-size: 12px; color: #6b7280;">📍 ${h.address}, ${h.city}</div>
      <div class="phone">📞 ${h.phone}</div>
      ${h.open24h ? '<span style="background: #10b981; color: white; padding: 2px 6px; border-radius: 4px; font-size: 10px;">Open 24/7</span>' : ''}
    </div>
  `).join('')}

  <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; text-align: center;">
    Generated by CeylonGuides • ${new Date().toLocaleDateString()}
  </div>
</body>
</html>
  `

    // Open in new window for printing
    const printWindow = window.open('', '_blank')
    if (printWindow) {
        printWindow.document.write(html)
        printWindow.document.close()
    }
}
